### ISSUE TITLE
About performance?

### ISSUE THREAD

**Issue by YamamotoSayaka** [doubleQ2018/Deep-learning-for-contact_map_v2#1]
Hi, thx for sharing this nice implementation. I'm also implementing this paper myself.
Are you able to achieve a similar performance as in the paper?
BTW, I see that you are using the original data from the RaptorX servers, right?
Can you share your performance on his testing set? 
( This part looks missing from the original paper, only results on CASP etc are reported. )

Many thanks!

**Comment by YamamotoSayaka** [comment]
Hi, after looking into the code, there are some parts different from the original paper.
It seems that training sequences with length greater than 300 are ignored, right?
And for the resnet, the resnet1d has only 1 block (should be 3 in the original paper) and resnet2d has 20 blocks.

Is it because of the memory issues, cuz I'm also having similar problems? @doubleQ2018

Looking forward for your reply

**Comment by doubleQ2018** [comment]
The datasets I used to compare with the original paper were 150 Pfam targets and 105 CASP11 targets, and the gap was about 3-4 points.

As you said, I excluded sequences > 300 because of the memory problem.

**Comment by YamamotoSayaka** [comment]
Hi, @doubleQ2018 , can you kindly share your pretrained model? : )
Many thanks anyway!!

**Comment by doubleQ2018** [comment]
Have updated in models.

**Comment by YamamotoSayaka** [comment]
Many thanks!!!

**Comment by YamamotoSayaka** [comment]
Hi @doubleQ2018 Sorry to bother again : ((
Loading the pretrained model with the default config gives me the following error

> InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:
Assign requires shapes of both tensors to match. lhs shape= [109] rhs shape= [105]

Did you change any configs or any part of the network?

**Comment by doubleQ2018** [comment]
Sorry for the problem, it seems that I used CCMpred only as 2D feature in this model. 
So you just need to change `input_2d = tf.placeholder("float", shape=[None, None, None, 5], name="input_x2")` to `input_2d = tf.placeholder("float", shape=[None, None, None, 1], name="input_x2")` in the line 26 of `test.py`, and feed only CCMpred as 2D feature.

I always used one 2D-feature of CCMpred in my later training. The original model with 5 2D-features has been overwritten, so I cannot provide it.

**Comment by doubleQ2018** [comment]
`test.py` has been updated, you can use it directly.

**Comment by YamamotoSayaka** [comment]
Much obliged : ))) Thank u so much !!!
