### ISSUE TITLE
data

### ISSUE THREAD

**Issue by Spr1nt0a0** [doubleQ2018/Deep-learning-for-contact_map_v2#3]
hi~could you share the data that you used in this implementation？thx a lot

**Comment by doubleQ2018** [comment]
You can download the dataset from the website of paper's author, https://ttic.uchicago.edu/~jinbo/datasets.htm

**Comment by Spr1nt0a0** [comment]
hi~ i have tried to download the dataset from the link above, while the speed is so slow, because my vpn has gone wrong, i'm sorry to ask that do you have any other way to share me with the dataset? thx!

**Comment by doubleQ2018** [comment]
I have graduated and the dataset is not available.

**Comment by Spr1nt0a0** [comment]
ok, thx for your reply!
